# Generated by Django 4.1.7 on 2023-08-09 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('date_of_birth', models.DateField(auto_now_add=True, null=True)),
                ('account_number', models.IntegerField(blank=True, default=0, null=True)),
                ('bank', models.CharField(blank=True, max_length=250, null=True)),
                ('referral_profit_made', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referred_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='vortex-logo.png', upload_to='site_images')),
                ('name', models.CharField(blank=True, default='vortex crypto exchange', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='support@xendex.com.ng', max_length=254, null=True)),
                ('address', models.CharField(blank=True, default='University of Nigeria, Nsukka, Enugu', max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('owned_by', models.CharField(blank=True, default='vortex', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cointype', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Note', models.CharField(blank=True, default='No notes added', max_length=100, null=True)),
                ('proof', models.ImageField(blank=True, default='screenshot.png', null=True, upload_to='trades-screenshots')),
                ('verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, default='support@xendex.com.ng', max_length=254, null=True)),
                ('Home_address', models.CharField(max_length=200)),
                ('Nin', models.CharField(blank=True, max_length=200, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cointype', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('naira_amount', models.CharField(blank=True, max_length=100)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.profile')),
            ],
        ),
    ]
