# Generated by Django 4.1.7 on 2023-08-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('sell_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
            ],
        ),
    ]
