# Generated by Django 4.1.7 on 2023-08-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busd', models.CharField(blank=True, max_length=250, null=True)),
                ('bnb_smartchain', models.CharField(blank=True, max_length=250, null=True)),
                ('bitcoin', models.CharField(blank=True, max_length=250, null=True)),
                ('bitcoin_cash', models.CharField(blank=True, max_length=250, null=True)),
                ('doge_coin', models.CharField(blank=True, max_length=250, null=True)),
                ('ethereum', models.CharField(blank=True, max_length=250, null=True)),
                ('litecoin', models.CharField(blank=True, max_length=250, null=True)),
                ('tron', models.CharField(blank=True, max_length=250, null=True)),
                ('usdt_bep20', models.CharField(blank=True, max_length=250, null=True)),
                ('usd_coin', models.CharField(blank=True, max_length=250, null=True)),
                ('usdt_trc20', models.CharField(blank=True, max_length=250, null=True)),
                ('binance_uid', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bank_details',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
