# Generated by Django 4.1.7 on 2023-08-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_wallet_alter_bank_details_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='solana',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
