# Generated by Django 4.1.7 on 2023-08-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_wallet_solana'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='Polygon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='XRP',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
