# Generated by Django 4.1.7 on 2023-08-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_wallet_polygon_wallet_xrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorder',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
