# Generated by Django 4.1.7 on 2023-08-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_sellorder_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorder',
            name='naira_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
