# Generated by Django 4.1.7 on 2023-08-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_buyorder_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
