# Generated by Django 4.1.7 on 2023-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_buyorder_proof_alter_site_logo_alter_site_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
