# Generated by Django 4.1.7 on 2023-08-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_profile_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
